# Generated by Django 5.1.7 on 2025-04-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.FloatField()),
                ('total', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('descripcion_pedido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descripcion_producto', models.TextField()),
                ('precio_producto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_topic', models.CharField(max_length=50)),
                ('descripcion_topic', models.TextField()),
                ('precio_topic', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Producto_Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField()),
                ('detalle_producto', models.TextField(blank=True, default='ninguno')),
                ('cantidad_topic', models.IntegerField()),
                ('detalle_topics', models.TextField(blank=True, default='ninguno')),
                ('fk_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Productos.pedidos')),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Productos.productos')),
                ('fk_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Productos.topics')),
            ],
        ),
    ]
