# Generated by Django 5.1.7 on 2025-03-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_Producto_Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_pedido', models.BigIntegerField()),
                ('fk_producto', models.BigIntegerField()),
                ('cantidad_producto', models.IntegerField()),
                ('fk_topic', models.BigIntegerField()),
                ('cantidad_topic', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.FloatField()),
                ('total', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('descripcion_pedido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descripcion_producto', models.TextField()),
                ('precio_producto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_topic', models.CharField(max_length=50)),
                ('descripcion_producto', models.TextField()),
                ('precio_producto', models.FloatField()),
            ],
        ),
    ]
