# Generated by Django 5.1.7 on 2025-04-27 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='estado_producto',
            field=models.TextField(choices=[('Activo', 'activo'), ('Deshabilitado', 'deshabilitado')], default='activo'),
        ),
        migrations.AddField(
            model_name='topics',
            name='estado_producto',
            field=models.TextField(choices=[('Activo', 'activo'), ('Deshabilitado', 'deshabilitado')], default='activo'),
        ),
        migrations.AlterField(
            model_name='pedido_producto',
            name='fk_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_pedido', to='Productos.pedidos'),
        ),
        migrations.AlterField(
            model_name='pedido_producto_topic',
            name='fk_id_pedido_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_de_producto', to='Productos.pedido_producto'),
        ),
    ]
