# Generated by Django 5.1.7 on 2025-04-22 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_producto_topic',
            name='fk_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Productos.productos'),
        ),
        migrations.AlterField(
            model_name='pedido_producto_topic',
            name='fk_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Productos.topics'),
        ),
    ]
