# Generated by Django 5.1.7 on 2025-04-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_producto_topic',
            name='detalle_producto',
            field=models.TextField(blank=True, default='ninguno'),
        ),
        migrations.AlterField(
            model_name='pedido_producto_topic',
            name='detalle_topics',
            field=models.TextField(blank=True, default='ninguno'),
        ),
    ]
