# Generated by Django 5.1.7 on 2025-03-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_producto_topic',
            name='detalle_producto',
            field=models.TextField(default='ninguno'),
        ),
        migrations.AddField(
            model_name='pedido_producto_topic',
            name='detalle_topics',
            field=models.TextField(default='ninguno'),
        ),
    ]
