# Generated by Django 6.0.4 on 2026-04-18 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='estado_producto',
            field=models.TextField(choices=[('Activo', 'activo'), ('Deshabilitado', 'deshabilitado')], default='activo'),
        ),
        migrations.AddField(
            model_name='productos',
            name='fecha_lanzado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topics',
            name='estado_topic',
            field=models.TextField(choices=[('Activo', 'activo'), ('Deshabilitado', 'deshabilitado')], default='activo'),
        ),
        migrations.AddField(
            model_name='topics',
            name='fecha_lanzado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido_producto',
            name='fk_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_pedido', to='Productos.pedidos'),
        ),
        migrations.AlterField(
            model_name='pedido_producto_topic',
            name='fk_id_pedido_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_de_producto', to='Productos.pedido_producto'),
        ),
        migrations.AlterModelTable(
            name='pedido_producto',
            table='productos_pedido_producto',
        ),
        migrations.AlterModelTable(
            name='pedido_producto_topic',
            table='productos_pedido_producto_topic',
        ),
        migrations.AlterModelTable(
            name='pedidos',
            table='productos_pedidos',
        ),
        migrations.AlterModelTable(
            name='productos',
            table='productos_productos',
        ),
        migrations.AlterModelTable(
            name='topics',
            table='productos_topics',
        ),
    ]
