# Generated by Django 5.1.7 on 2025-04-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_pedido_producto_topic_fk_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(max_length=15),
        ),
    ]
