# Generated by Django 5.1.7 on 2025-04-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_productos_estado_producto_topics_estado_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='estado_producto',
            new_name='estado_topic',
        ),
    ]
