# Generated by Django 5.1.7 on 2025-05-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_rename_estado_producto_topics_estado_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='fecha_lanzado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topics',
            name='fecha_lanzado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
