# Generated by Django 5.0.6 on 2025-08-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_pedidos_fecha_pedido_productos_fecha_lanzado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fecha_lanzado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='fecha_lanzado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
