# Generated by Django 5.1.7 on 2025-08-29 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_alter_pedidos_fecha_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido_producto',
            table='productos_pedido_producto',
        ),
        migrations.AlterModelTable(
            name='pedido_producto_topic',
            table='productos_pedido_producto_topic',
        ),
        migrations.AlterModelTable(
            name='pedidos',
            table='productos_pedidos',
        ),
        migrations.AlterModelTable(
            name='productos',
            table='productos_productos',
        ),
        migrations.AlterModelTable(
            name='topics',
            table='productos_topics',
        ),
    ]
